# Generated by Django 4.2.21 on 2025-06-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.productlisting'),
        ),
    ]
