# Generated by Django 4.2.21 on 2025-06-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_orderitem_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
