# Generated by Django 4.2.21 on 2025-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
    ]
