# Generated by Django 4.2.21 on 2025-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_productlisting_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
    ]
