# Generated by Django 4.2.21 on 2025-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_product_is_approved_alter_productlisting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='status',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='admin_status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='supervisor_status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
