# Generated by Django 4.2.21 on 2025-07-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_wishlistrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.wishlistrequest'),
        ),
    ]
